<?php

namespace AppBundle\Repository;

/**
 * GalerieAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalerieAnnonceRepository extends \Doctrine\ORM\EntityRepository
{
}