app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
users:
    type:     rest
    resource: AppBundle\Controller\UserController

annonces:
    type:     rest
    resource: AppBundle\Controller\AnnoncesController
